language: python

services:
  - docker

before_install:
  - docker-compose up -d --build api
  - docker ps -a
  - docker exec summarizer-server sh -c "cd /server && pip3 install black && black --check ."

script:
  - black --check .
