dist: xenial   # required for Python >= 3.7

stages:
  - test

jobs:
  include:
    - stage: test
      language: python
      python: 3.7
      install:
        - make install
        # need to run this because we're not running image_setup
        - python3.7 -c "import nltk; nltk.download('punkt')"
      script:
        - black --check .
        - make test
