version: "3"

services:
  api:
    image: summarizer_server
    container_name: summarizer_server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    network_mode: "bridge"
    environment: # forward these from shell to the container at runtime
      - DEBUG
      - PORT
      - JOBLIB_MULTIPROCESSING=0
    command: [
      "uwsgi",
      "--thunder-lock",
      # "--uid", "uwsgi",
      # "--protocol", "uwsgi",
      "--socket", ":5000",
      "--chmod-socket",
      "--chdir", "/server/summarizer_server",
      "--module", "server",
      "--master",
      # "--wsgi-file", "summarizer_server/server.py",
      "--callable", "app",
      # "--plugin", "python37",
      # "--ini", "/server/summarizer_server/uwsgi.ini",
      "--enable-threads",
      "--processes", "4",
    ]
  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "./summarizer_server/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    network_mode: "bridge"
    links:
      - api
    depends_on:
      - api
