version: "3.4"

services:
  api:
    image: gcr.io/alpine-gasket-242504/summarizer-server:latest
    container_name: summarizer_server
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    network_mode: "bridge"
    environment: # forward these from shell to the container at runtime
      - DEBUG
      - PORT
      - JOBLIB_MULTIPROCESSING=0 # this removes a uwsgi warning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_URL=postgres
      - POSTGRES_DB=postgres
      - ENV
      - DD_API_KEY
      - HOST
    volumes:
      - "/var/log/docker:/var/log/"
    links:
      - postgres
    depends_on:
      - postgres
    command: [
      "uwsgi",
      "--thunder-lock",
      "--socket", ":5000",
      "--chmod-socket",
      "--chdir", "/server/summarizer_server",
      "--module", "server",
      "--master",
      "--callable", "app",
      "--processes", "2",
      "--logto", "/var/log/api.log",
    ]
  nginx:
    image: nginx:1.17
    container_name: summarizer_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./summarizer_server/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./summarizer_server/nginx.key:/etc/nginx/ssl/nginx.key:ro"
      - "./summarizer_server/nginx.crt:/etc/nginx/ssl/nginx.crt:ro"
    network_mode: "bridge"
    links:
      - api
    depends_on:
      - api
  postgres:
    image: postgres:12.0
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    network_mode: "bridge"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
    name: postgres_data
