version: "3"

services:
  api:
    image: summarizer_server
    container_name: summarizer_server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    network_mode: "bridge"
    environment: # forward these from shell to the container at runtime
      - DEBUG
      - PORT
