version: "3"

services:
  api:
    image: gcr.io/alpine-gasket-242504/summarizer-server:latest
    container_name: summarizer_server
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    network_mode: "bridge"
    environment: # forward these from shell to the container at runtime
      - DEBUG
      - PORT
      - JOBLIB_MULTIPROCESSING=0 # this removes a uwsgi warning
    volumes:
      - "/var/log/docker:/var/log/"
    command: [
      "uwsgi",
      "--thunder-lock",
      "--socket", ":5000",
      "--chmod-socket",
      "--chdir", "/server/summarizer_server",
      "--module", "server",
      "--master",
      "--callable", "app",
      "--processes", "2",
      "--logto", "/var/log/uwsgi.log",
    ]
  nginx:
    image: nginx:1.17
    container_name: summarizer_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./summarizer_server/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./summarizer_server/nginx.key:/etc/nginx/ssl/nginx.key:ro"
      - "./summarizer_server/nginx.crt:/etc/nginx/ssl/nginx.crt:ro"
    network_mode: "bridge"
    links:
      - api
    depends_on:
      - api
