version: "3"

services:
  api:
    image: summarizer-server
    container_name: summarizer-server
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    network_mode: "bridge"
